### ISSUE TITLE
UnhandledException ETIMEDOUT when downloading resources

### ISSUE THREAD

**Issue by Andrzejone** [TotomInc/darkorbit-resource-downloader#1]
![image](https://user-images.githubusercontent.com/39127677/128219691-5fdf9347-344f-4a99-9cb0-37ed85ddd17f.png)
 It's like poping up always. Whenever I try download all 3 kind of assets from menu or only one.

**Comment by TotomInc** [comment]
Thanks for the issue. It looks like an URL is broken from the DarkOrbit resource server, which cause a timeout on a specific resource URL.

I'll try to publish a fix tomorrow to handle the error exception, so the program will not crash anymore when timeout happens.

**Comment by TotomInc** [comment]
@Andrzejone I've fixed the error.

Make sure to update your repo locally to benefit from the latest changes. The issue should be resolved, but feel free to re-open it if it's still not solved.

Thanks for the report!

**Comment by Andrzejone** [comment]
Don't know what doing wrong.
fresh new folder, did steps in readme.
![image](https://user-images.githubusercontent.com/39127677/130366898-bbb378fb-abef-4cb7-a42d-0be1caf19e3e.png)
